name = "meta-ai-scheduler-backend"
main = "src/worker.js"
compatibility_date = "2025-11-18"

[[d1_databases]]
binding = "DB"
database_id = "fc9d50c4-7ef1-4b22-a7fa-3975015322f6"
database_name = "meta_ai_scheduler"
migrations_dir = "migrations"

[triggers]
crons = ["*/5 * * * *"]
